export const API_ENDPOINTS = {
  AUTH: {
    SIGNUP: '/api/auth/signup',
    ACTIVATE: '/api/auth/activate',
    LOGIN: '/api/auth/login',
    REFRESH: '/api/auth/refresh-token',
    LOGOUT: '/api/auth/logout',
    ME: '/api/auth/me',
  },
  ADMIN: {
    GENERATE_CODES: '/api/admin/access-codes/generate',
    LIST_CODES: '/api/admin/access-codes',
  },
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
};

export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  INVALID_ACCESS_CODE: 'INVALID_ACCESS_CODE',
  EXPIRED_CODE: 'EXPIRED_CODE',
  CODE_ALREADY_USED: 'CODE_ALREADY_USED',
  CODE_USAGE_LIMIT_REACHED: 'CODE_USAGE_LIMIT_REACHED',
  ACCOUNT_NOT_ACTIVATED: 'ACCOUNT_NOT_ACTIVATED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};
